# Data analysis and visualization in R

*Written by Keaka Farleigh on August 5th, 2025*

*Last updated by Keaka Farleigh on August July 8th, 2025*

*I am updating this chapter. The new version will be posted by July 27th, 2026. Please email me if you need help with data analysis and visualization!*

## Purpose

This tutorial will give you an introduction to data analysis and visualization. You will learn how to perform some basic analyses and how to visualize those results. I will assume that you have minimal experience with R and are a beginner user. Please read through the [Introduction to R chapter](https://kfarleigh.github.io/ResearchersGuideToPopulationGenomics/introduction-to-r.html) or send me an email if you do not feel comfortable with this tutorial. 

## Learning objectives

- Learn how to choose a statistical analysis.
- Learn how to estimate correlation between two variables.
- Learn how to perform linear regression.
- Learn how to perform a t-test.
- Learn best practices for plotting.
- Learn how to make scatter plots.
- Learn how to make boxplots.
- Learn how to make a multipanel figure.

## Files required for this pipeline

None!

## Programs used in this pipeline

 - [R](https://www.r-project.org/) (R core team, 2025)
 - [Rstudio](https://posit.co/download/rstudio-desktop/)
 - [tidyverse packages](https://tidyverse.org/)
 
 
Install the tidyverse using the command below.

```{r install tidyverse data analysis, echo=TRUE, eval=FALSE}

install.packages("tidyverse")

library(tidyverse)

# Load data
data(iris)

```


## Notes on this tutorial

The materials in this tutorial were originally developed as part of the [Lambda](https://sites.miamioh.edu/lambda/) bioinformatic workshop at Miami University by Dr. Tereza Jezkova and Dr. Alfredo Ascanio. These materials are now presented at Lambda and the Foundations in R workshop at the University of Virginia.

## Overview

This tutorial will be broken into separate sections for data analysis and visualization, respectively. We will walk through the basics of analysis and visualization before working through some examples!

## Data analysis

We analyze data to understand the relationships between variables in our data and extract meaningful insights that help us understand the processes driving those relationships, make decisions, and much more. Without data analysis there is not much for us to visualize or do in a study. 

### How to choose a statistical method

A critical part of data analysis is making sure that you are using the right method to analyze your data. This depends on the characteristics of your data and what we would like to test. A dataset, for example, may have different types of variables. Some may be numerical values on a continous scale (e.g., temperature), while others may represent different classes (e.g., level of education, land cover type). We will walk through a few commonly used analyses, when they are appropriate, and how to perform them in R. 

### Correlation

Evaluate the correlation between two variables is a common first step in many studies. Correlations use two continous variables and determines the relationship between them. If one variable increases with the other then these variables are postively correlated. If one increases when the other decreases they are negatively correlated. Correlations typically range from -1 to 1. 

In R, we use the `cor` function to evaluate the correlation between two variables and the `cor.test`function to test if the correlation is significantly different than 0.

We can ask, for example, are the Sepal and Petal lengths of flowers in the iris dataset correlated? Is this correlation different from 0?

```{correlation tests, echo = TRUE, eval = FALSE}

cor(x = iris$Petal.Length, y = iris$Sepal.Length)

cor.test(x = iris$Petal.Length, y = iris$Sepal.Length)

```

Note that there are different kinds of correlations you can perform. Check out the method argument of the `cor` and `cor.test` functions to learn about them. 

### Regression 

### T-test

## Data visualization

### Scatterplot

### Boxplot

### Multipanel figure

## References

R Core Team (2025). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. https://www.R-project.org/.

Wickham, H., et al. (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686. https://doi.org/10.21105/joss.01686
